pipeline {
    agent any

    environment {
        NODE_VERSION    = "18"
        DOCKER_IMAGE    = "mazenmostafa429/gig-router-frontend"
        DOCKER_REGISTRY = "https://index.docker.io/v1/"
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Setup Node') {
            steps {
                sh """
                echo "Setting Node version ${NODE_VERSION}"
                npm install ${NODE_VERSION}
                npm use ${NODE_VERSION}
                node -v
                npm -v
                """
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Build Project') {
            steps {
                sh 'npm run build'
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ."
                    docker.withRegistry("${DOCKER_REGISTRY}", 'docker-cred') {
                        docker.image("${DOCKER_IMAGE}:${BUILD_NUMBER}").push()
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully"
        }
        failure {
            echo "❌ Pipeline failed – check logs"
        }
    }
}
