pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "mazenmostafa429/gig-router-frontend"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/mazenmostafa001/end-to-end-microservices-django-react-ci-.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('frontend') { // <- عدلي حسب مكان package.json
                    sh 'npm install'
                }
            }
        }

        stage('Build Project') {
            steps {
                dir('frontend') { // <- نفس هنا
                    sh 'npm run build'
                }
            }
        }

        stage('Docker Build & Push') {
            steps {
                dir('frontend') { // <- لو عايزة Docker image
                    script {
                        sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ."
                        docker.withRegistry('https://index.docker.io/v1/', 'docker-cred') {
                            docker.image("${DOCKER_IMAGE}:${BUILD_NUMBER}").push()
                        }
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline completed successfully"
        }
        failure {
            echo "❌ Pipeline failed – check logs"
        }
    }
}
