version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build: ./backend
    container_name: celery
    command: celery -A gig_router worker -l info
    env_file:
      - .env
    depends_on:
      - backend
      - redis

volumes:
  postgres_data:


#   version: "3.9"

# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: backend
#     command: python manage.py runserver 0.0.0.0:8000
#     volumes:
#       - ./backend:/app
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env
#     depends_on:
#       - db
#       - redis

#   frontend:
#     build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     container_name: frontend
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend

#   db:
#     image: postgres:15
#     container_name: db
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

#   redis:
#     image: redis:7
#     container_name: redis
#     ports:
#       - "6379:6379"

#   celery:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     container_name: celery
#     command: celery -A gig_router worker -l info
#     env_file:
#       - .env
#     depends_on:
#       - backend
#       - redis

# volumes:
#   postgres_data:
